export const GROUPS_FETCH = 'GROUPS_FETCH'
export const GROUPS_CATEGORIES_FETCH = 'GROUPS_CATEGORIES_FETCH'

export const JOBS_FETCH = 'JOBS_FETCH'

export const LOCATIONS_FETCH = 'LOCATIONS_FETCH'

export const STATES_FETCH = 'STATES_FETCH'

export const WORK_CATEGORIES_FETCH = 'WORK_CATEGORIES_FETCH'

export const WORK_LEVELS_FETCH = 'WORK_LEVELS_FETCH'

export const WORK_TYPES_FETCH = 'WORK_TYPES_FETCH'
