name: CRON Rebuild Site

on:
  schedule:
    - cron: "0 1/5 * * *"

jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      uses: wei/curl@master
      with:
        args: https://api.zeit.co/v1/integrations/deploy/QmdUckg81pGZMobwiWC9EwA2WfbvfHfbfU8nMtfShkPES7/2ah34aWIPZ
